### ISSUE TITLE
Improvements Checklist

### ISSUE THREAD

**Issue by nackjicholson** [nackjicholson/generator-react-hapi-universal#1]
- [ ] Change name of `code` function to `serveUniversalApp`
- [ ] Complicate the example to make it load data server side using `renderProps` and static methods on the route handler components. See the bottom of these [redux docs](http://rackt.github.io/redux/docs/recipes/ServerRendering.html)
- [ ] Possibly make a fork of this repo that uses redux and router together `generator-redux-hapi-universal`

**Comment by nackjicholson** [comment]
Never happening.
